"""End-to-end evaluations on top of Dakota runs."""

from itis_sumo.evaluate.funs_evaluate import (
    compute_coverage,
    compute_cv_accuracy_metrics,
    compute_cv_convergence,
    compute_cv_diagnostics,
    compute_paired_ttest,
    evaluate_sobol_indices,
    evaluate_sumo,
    evaluate_sumo_along_axes,
    evaluate_sumo_crossvalidation,
    evaluate_sumo_manual_crossvalidation,
    evaluate_sumo_on_grid,
    export_sumo_model,
    fit_convergence_exponential,
    fit_convergence_exponential_asymptotic,
    import_sumo_model,
    perform_moga_optimization,
    propagate_uq,
    retrieve_csv_result,
)

__all__ = [
    "compute_coverage",
    "compute_cv_accuracy_metrics",
    "compute_cv_convergence",
    "compute_cv_diagnostics",
    "compute_paired_ttest",
    "evaluate_sobol_indices",
    "evaluate_sumo",
    "evaluate_sumo_along_axes",
    "evaluate_sumo_crossvalidation",
    "evaluate_sumo_manual_crossvalidation",
    "evaluate_sumo_on_grid",
    "export_sumo_model",
    "fit_convergence_exponential",
    "fit_convergence_exponential_asymptotic",
    "import_sumo_model",
    "perform_moga_optimization",
    "propagate_uq",
    "retrieve_csv_result",
]
